//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `AppInterfaces.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package AppInterfaces;

public class Integral extends com.zeroc.Ice.Value
{
    public Integral()
    {
        this.functionnString = "";
    }

    public Integral(String functionnString, double lowerRange, double upperRange)
    {
        this.functionnString = functionnString;
        this.lowerRange = lowerRange;
        this.upperRange = upperRange;
    }

    public String functionnString;

    public double lowerRange;

    public double upperRange;

    public Integral clone()
    {
        return (Integral)super.clone();
    }

    public static String ice_staticId()
    {
        return "::AppInterfaces::Integral";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1745127817L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(functionnString);
        ostr_.writeDouble(lowerRange);
        ostr_.writeDouble(upperRange);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        functionnString = istr_.readString();
        lowerRange = istr_.readDouble();
        upperRange = istr_.readDouble();
        istr_.endSlice();
    }
}
